/* =============================================================
   EBIKESCENTER — MANIFEST DE CONTENIDO EDITABLE
   Edita este archivo con el Bloc de notas para cambiar textos,
   modelos, servicios, galería e información de contacto.
   NO borres las comas ni las comillas.
   ============================================================= */

(function () {
  window.__EBIKES__ = {

    /* ── MARCA ────────────────────────────────────────────── */
    brand: {
      name:       'EBikesCenter',
      tagline:    'Muévete. Sin límites.',
      address:    'Calle Gran Vía 45, Madrid',
      metro:      'Metro Gran Vía / Callao',
      phone:      '910 55 66 77',
      whatsapp:   '+34910556677',
      instagram:  '@ebikescenter.madrid',
      instagramUrl:'https://instagram.com/ebikescenter.madrid',
      hours:      'Lun – Sáb · 10:00 → 20:00',
      established:'EST. 2020 · MAD',
      mapEmbed:   'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3037.6!2d-3.703!3d40.4200!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDDCsDI1JzEyLjAiTiAzwrA0MicxMC44Ilc!5e0!3m2!1ses!2ses!4v1700000000000',
    },

    /* ── MODELOS (10 BICIS) ───────────────────────────────── */
    bikes: [
      {
        id:          'urban-pro',
        name:        'Urban Pro',
        series:      'City',
        glass:       'diamond',
        subtitle:    'La commuter definitiva',
        specs:       ['Motor 250W Bafang', 'Batería 504 Wh', 'Autonomía 120 km', 'Display LCD integrado'],
        description: 'Diseñada para tragarse el asfalto diario sin sudar. Ligera, silenciosa y con autonomía para ir y volver dos veces. La bici que convierte el trayecto al trabajo en el mejor momento del día.',
        liquid:      '#1a4a8a',
        accent:      '#00C2FF',
        price:       '2.490 €',
      },
      {
        id:          'trail-x',
        name:        'Trail X',
        series:      'MTB',
        glass:       'full-sus',
        subtitle:    'Conquista cualquier terreno',
        specs:       ['Motor 750W Bosch', 'Batería 720 Wh', 'Suspensión delantera 120mm', 'Frenos hidráulicos'],
        description: 'Potencia real para rutas reales. Sube donde otros se bajan a empujar. Suspensión delantera, neumáticos 29", y un motor que no entiende de cuestas imposibles.',
        liquid:      '#0d3b1f',
        accent:      '#39FF14',
        price:       '3.290 €',
      },
      {
        id:          'cargo-s',
        name:        'Cargo S',
        series:      'Cargo',
        glass:       'longtail',
        subtitle:    'Lleva más, pedalea menos',
        specs:       ['Motor 500W Mid-Drive', 'Batería 630 Wh', 'Carga útil 150 kg', 'Portaequipaje XL'],
        description: 'La furgoneta que no necesita aparcamiento. Compra, niños, pedidos — todo cabe. Construida para aguantar la carga diaria sin perder un gramo de agilidad urbana.',
        liquid:      '#7a3a0a',
        accent:      '#FF6B00',
        price:       '3.890 €',
      },
      {
        id:          'fold-mini',
        name:        'Fold Mini',
        series:      'Plegable',
        glass:       'folding',
        subtitle:    'Tu ciudad en tu mochila',
        specs:       ['Motor 250W trasero', 'Batería 360 Wh', 'Peso 14 kg', 'Plegado en 15 segundos'],
        description: 'Metro, oficina, maletero — entra en todos. La solución definitiva para el último kilómetro. Ligera como una bolsa de deporte, potente como una bici de verdad.',
        liquid:      '#1a3a6a',
        accent:      '#00C2FF',
        price:       '1.790 €',
      },
      {
        id:          'speed-45',
        name:        'Speed 45',
        series:      'Speed',
        glass:       'speed',
        subtitle:    'Hasta 45 km/h homologada',
        specs:       ['Motor 500W Speed Pedelec', 'Batería 630 Wh', 'Velocidad máx. 45 km/h', 'Requiere carnet AM'],
        description: 'Cuando el tiempo es tuyo pero la ciudad no lo sabe. Legalmente a 45 km/h, sin atascos, sin gasolina. Para los que llevan el ritmo de la ciudad por delante.',
        liquid:      '#6a1a1a',
        accent:      '#FF6B00',
        price:       '4.190 €',
      },
      {
        id:          'gravel-e',
        name:        'Gravel E',
        series:      'Gravel',
        glass:       'gravel',
        subtitle:    'Asfalto y tierra, lo mismo',
        specs:       ['Motor 250W Shimano', 'Batería 504 Wh', 'Neumáticos mixtos 700×40', 'Autonomía 110 km'],
        description: 'Sale de la ciudad y no para. Geometría de grava, asistencia eléctrica inteligente. Para los que el fin de semana empieza en la puerta de casa y termina donde llega la carretera.',
        liquid:      '#1a3a14',
        accent:      '#39FF14',
        price:       '2.890 €',
      },
      {
        id:          'comfort-plus',
        name:        'Comfort Plus',
        series:      'Touring',
        glass:       'dutch',
        subtitle:    'Kilómetros sin esfuerzo',
        specs:       ['Motor 250W central', 'Batería 630 Wh', 'Sillín ergonómico GEL', 'Portabicicleta trasero'],
        description: 'Para los que quieren llegar, no llegar sudados. Posición cómoda, amortiguación suave, y un motor que hace el trabajo cuando tú decides descansar. Turismo eléctrico.',
        liquid:      '#2a3a4a',
        accent:      '#00C2FF',
        price:       '2.190 €',
      },
      {
        id:          'kids-power',
        name:        'Kids Power',
        series:      'Junior',
        glass:       'kids',
        subtitle:    'Para los que vienen detrás',
        specs:       ['Motor 180W suave', 'Batería 252 Wh', 'Talla 20"-24" adaptable', 'Limitador de velocidad parental'],
        description: 'La primera bici eléctrica que un niño no olvida. Ligera, segura y con el justo de potencia para que la aventura sea suya. El limitador parental es para los padres; la sonrisa, solo para ellos.',
        liquid:      '#4a3a0a',
        accent:      '#39FF14',
        price:       '990 €',
      },
      {
        id:          'trekking-pro',
        name:        'Trekking Pro',
        series:      'Trekking',
        glass:       'trekking',
        subtitle:    'De la ciudad a la montaña',
        specs:       ['Motor 500W Bosch Performance', 'Batería 720 Wh', 'Autonomía 150 km', 'Iluminación integrada'],
        description: 'Versátil sin concesiones. Rueda por el carril bici, sale por la pista forestal y vuelve a casa con batería de sobra. La bici para los que no quieren elegir entre ciudad y naturaleza.',
        liquid:      '#0d1a3a',
        accent:      '#00C2FF',
        price:       '3.490 €',
      },
      {
        id:          'road-race',
        name:        'Road Race',
        series:      'Racing',
        glass:       'road',
        subtitle:    'Velocidad con asistencia',
        specs:       ['Motor 250W ultraligero', 'Batería 504 Wh integrada', 'Peso 11 kg', 'Geometría race'],
        description: 'Para los ciclistas de verdad que quieren ir más lejos sin llegar más tarde. Geometría de carretera, asistencia invisible, kilómetros de más en cada salida. No hace trampa; multiplica.',
        liquid:      '#1a1a2a',
        accent:      '#39FF14',
        price:       '3.990 €',
      },
    ],

    /* ── SERVICIOS ────────────────────────────────────────── */
    services: [
      {
        days:        'Lun – Mié',
        name:        'Taller Express',
        description: 'Revisión completa en 24 horas.',
        icon:        'wrench',
        accent:      '#00C2FF',
      },
      {
        days:        'Jueves',
        name:        'Test Ride',
        description: 'Prueba sin compromiso. Llévate la que quieras.',
        icon:        'bike',
        accent:      '#39FF14',
      },
      {
        days:        'Viernes',
        name:        'Asesoría Personalizada',
        description: 'Te ayudamos a elegir la bici de tu vida.',
        icon:        'chat',
        accent:      '#FF6B00',
      },
      {
        days:        'Sábado',
        name:        'Ruta Grupal',
        description: 'Salida con la comunidad. 10:00 desde la tienda.',
        icon:        'map',
        accent:      '#00C2FF',
      },
    ],

    /* ── GALERÍA ──────────────────────────────────────────── */
    gallery: [
      { src: 'assets/img/gallery-01.webp', alt: 'Bicicleta eléctrica urbana en movimiento' },
      { src: 'assets/img/gallery-02.webp', alt: 'Detalle motor e-bike' },
      { src: 'assets/img/gallery-03.webp', alt: 'Ruta en bicicleta eléctrica de montaña' },
      { src: 'assets/img/gallery-04.webp', alt: 'Batería de bicicleta eléctrica' },
      { src: 'assets/img/gallery-05.webp', alt: 'Taller de reparación e-bikes' },
      { src: 'assets/img/gallery-06.webp', alt: 'Ciclista urbano con e-bike' },
      { src: 'assets/img/gallery-07.webp', alt: 'Cargo bike cargada en ciudad' },
      { src: 'assets/img/gallery-08.webp', alt: 'Display digital bicicleta eléctrica' },
      { src: 'assets/img/gallery-09.webp', alt: 'Grupo de ciclistas en ruta eléctrica' },
      { src: 'assets/img/gallery-10.webp', alt: 'Bicicleta plegable eléctrica' },
      { src: 'assets/img/gallery-11.webp', alt: 'Freno hidráulico e-bike MTB' },
      { src: 'assets/img/gallery-12.webp', alt: 'Rueda trasera con motor integrado' },
      { src: 'assets/img/gallery-13.webp', alt: 'Interior tienda EBikesCenter' },
      { src: 'assets/img/gallery-14.webp', alt: 'Bicicleta eléctrica de carretera' },
      { src: 'assets/img/gallery-15.webp', alt: 'Test ride en carril bici Madrid' },
      { src: 'assets/img/gallery-16.webp', alt: 'Detalle manillar con display GPS' },
    ],

  };
})();
